module.exports = {
	Card: require('./Card').Card,
	Event: require('./Event').Event,
	Favourite: require('./Favourite').Favourite,
	Message: require('./Message').Message,
	Note: require('./Note').Note,
	SharedCard: require('./SharedCard').SharedCard,
	Speaker: require('./Speaker').Speaker,
	Topic: require('./Topic').Topic,
	Upload: require('./Upload').Upload,
	User: require('./User').User,
	Message: require('./Message').Message,
	UserFile: require('./UserFile').UserFile,
	Geolocation: require('./Geolocation').Geolocation,
	EmailNotification: require('./EmailNotification').EmailNotification,
	SocialMetadata: require('./SocialMetadata').SocialMetadata,
	Avatar: require('./Avatar').Avatar,
	Attendee: require('./Attendee').Attendee,
	EventMessage: require('./EventMessage').EventMessage,
	Ticket: require('./Ticket').Ticket
}