module.exports = {
	Attendee: require('./Attendee').Attendee,
	Card: require('./Card').Card,
	CardType: require('./CardType').CardType,
	Event: require('./Event').Event,
	Favourite: require('./Favourite').Favourite,
	Message: require('./Message').Message,
	Note: require('./Note').Note,
	SharedCard: require('./SharedCard').SharedCard,
	Speaker: require('./Speaker').Speaker,
	Topic: require('./Topic').Topic,
	Upload: require('./Upload').Upload,
	User: require('./User').User,
	UserFile: require('./UserFile').UserFile,
}